name 'example42-syslog-ng'
version '2.0.11'

author 'Alessandro Franceschi'
license 'Apache2'
project_page 'http://www.example42.com'
source 'https://github.com/example42/puppet-syslog-ng'
summary 'Puppet module for syslog-ng'
description 'This module installs and manages syslog-ng. Check README for details.'
dependency 'example42/puppi', '>=2.0.0'
dependency 'example42/firewall', '>=2.0.0'
dependency 'example42/monitor', '>=2.0.0'
